version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: curl -sL https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o protoc.zip 
      - run: sudo apt-get update
      - run: sudo apt-get install unzip
      - run: unzip protoc.zip
      - run: ./bin/protoc proto/messages.proto --js_out .

